### ISSUE TITLE
this is no issue

### ISSUE THREAD

**Issue by Chriscxa** [tipsyphp/tipsy#46]
First, absolute great work.
Wish more basic like security (ajax, crossSiteScripting, tokken-cookie. validation  etc.) like this base: https://github.com/OmarElGabry/miniPHP
..but in mvw
...with userroles.

great work.

**Comment by arzynik** [comment]
thanks! 

closing in favor of https://github.com/tipsyphp/tipsy/issues/48 and https://github.com/tipsyphp/tipsy/issues/47
